### ISSUE TITLE
Make sure all concepts are applied before validating any constraints

### ISSUE THREAD

**Issue by odrotbohm** [buschmais/jqa-core-framework#13]
In situations in which there's no direct dependency between a concept and constraint, the evaluation order might end up wrong as the execution doesn't prioritize the concept evaluation. Let me give you an example from the jQA Spring plugin:

There are two set of rules: one for Spring Framework, one for Spring Boot. The Spring Framework one wants to defined the following things:

- A concept that adds a label `Configuration` to all classes annotated with `@Configuration`
- A constraint that requires methods annotated with `@Bean` to only live in classes labeled with `Configuration`. That constraint adds a `<requireConstraint … />` to point to the declared constrained.

Spring Boot now defines an annotation `@SpringBootApplication` that is meta-annotated with `@Configuration`. Due to jQA's limitation to not process annotation types any further – and thus not detecting the meta-annotation. As a workaround I now declare an additional concept that simply labels classes annotations with `@SpringBootAnnotation` with `Configuration`, too, but want to keep that in the file that has Boot specific rules and concepts so that I cannot refer to the Boot specific concept from within the Spring specific constraint.

Here's now the output I get from a project using the plugin:

```
[INFO] Validating constraint 'spring-injection:BeanProducerMustBeDeclaredInConfigurationComponent' with severity: 'MAJOR'.
…
[INFO] Applying concept 'spring-boot:Application' with severity: 'MINOR'.
…
```

As you can see, the constraint is evaluated *before* the concept is applied.

That scenario can actually broadened to all cases in which pretty generic concepts are introduced that certain plugins could contribute to, but the generic module already defining a constraint based on those generic concepts. Imaging a rule working with the concepts of "newables" and "injectables" and a rule that injectables are allowed to use newables but not vice versa. We can now have e.g. the JPA plugin contributing JPA entities, mapped superclasses etc. as newables and both the CDI plugin as well as the Spring one contributing to newables based on their way to describe components.

**Comment by DirkMahler** [comment]
Seems that the final solution needs to be a bit different, i.e. all concepts of a parent group and all nested groups (including their declared concepts) will be executed before the constraints of that group are verified - otherwise the semantics of a group containing concepts and constraints gets blurred from a user perspective as well as from the implementation.

This would still allow for executing concepts which contribute labels, etc. for constraints that are declared in nested groups without an explicit dependency. The precondition is that the user must place such concepts in the same group that also includes the nested group for execution. This restriction can be seen as a disadvantage and advantage at the same time: the latter is that the user is forced into a structure that keeps related rules close together (a kind of cohesion).

Hope I didn't miss anything important here, comments welcome...
